import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ClientOnly from "@/components/ClientOnly";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClientOnly>
        <body
          className={
            "bg-gradient-to-r from-blue-600 via-blue-500 to-blue-600 text-white"
          }>
          <Navbar />
          {children}
        </body>
      </ClientOnly>
    </html>
  );
}
